#!/bin/env bash

total=0
highest_user=""
highest_usage=0
over_1000=0

while read -r user usage
do
    total=$(( total + usage ))

    if (( usage > highest_usage )); then
        highest_usage=$usage
        highest_user=$user
    fi

    if (( usage > 1000 )); then
        (( over_1000++ ))
    fi
done

echo "Total usage: $total MB"
echo "Highest user: $highest_user ($highest_usage MB)"
echo "Users over 1000 MB: $over_1000"
